# Game Logic Constants
ROWS = 20
COLS = 20

# Pygame Display Constants
SCREEN_BASE_WIDTH = 600
SCREEN_BASE_HEIGHT = 600
MOVE_INTERVAL_PLAY = 100  # Milliseconds, speed for playable game
LINE_WIDTH = 1

OUTER_RECT_X = 50
OUTER_RECT_Y = 50
OUTER_RECT_WIDTH = 500
OUTER_RECT_HEIGHT = 500

CELL_WIDTH = OUTER_RECT_WIDTH // COLS
CELL_HEIGHT = OUTER_RECT_HEIGHT // ROWS
INNER_CELL_WIDTH = CELL_WIDTH - (LINE_WIDTH * 2)
INNER_CELL_HEIGHT = CELL_HEIGHT - (LINE_WIDTH * 2)

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
SNAKE_COLOR = (0, 255, 0)
APPLE_COLOR = (255, 0, 0)